import 'package:mathpunk_cardgame/classes/card/anger.card.dart';
import 'package:mathpunk_cardgame/classes/card/bash.card.dart';
import 'package:mathpunk_cardgame/classes/card/body_slam.card.dart';
import 'package:mathpunk_cardgame/classes/card/clash.card.dart';
import 'package:mathpunk_cardgame/classes/card/cleave.card.dart';
import 'package:mathpunk_cardgame/classes/card/clothes_line.card.dart';
import 'package:mathpunk_cardgame/classes/card/defend.card.dart';
import 'package:mathpunk_cardgame/classes/card/flex.card.dart';
import 'package:mathpunk_cardgame/classes/card/headbutt.card.dart';
import 'package:mathpunk_cardgame/classes/card/heavy_blade.card.dart';
import 'package:mathpunk_cardgame/classes/card/iron_wave.card.dart';
import 'package:mathpunk_cardgame/classes/card/perfect_strike.card.dart';
import 'package:mathpunk_cardgame/classes/card/pommel_strike.card.dart';
import 'package:mathpunk_cardgame/classes/card/strike.card.dart';
import 'package:mathpunk_cardgame/classes/card/thunderclap.card.dart';
import 'package:mathpunk_cardgame/classes/card/true_gift.card.dart';
import 'package:mathpunk_cardgame/classes/card/twin_strike.card.dart';
import 'package:mathpunk_cardgame/classes/card/warcry.card.dart';

final strikeCard = StrikeCard();
final bashCard = BashCard();
final defendCard = DefendCard();
final angerCard = AngerCard();
final bodySlamCard = BodySlamCard();
final clashCard = ClashCard();
final cleaveCard = CleaveCard();
final clothesLineCard = ClothesLineCard();
final flexCard = FlexCard();
final headbuttCard = HeadbuttCard();
final heavyBladeCard = HeavyBladeCard();
final ironWaveCard = IronWaveCard();
final perfectStrikeCard = PerfectStrikeCard();
final pommelStrikeCard = PommelStrikeCard();
final thunderclapCard = ThunderclapCard();
final trueGiftCard = TrueGiftCard();
final twiStrikeCard = TwinStrikeCard();
final warcryCard = WarCryCard();
