import 'package:spire_mvp_flutter/classes/card/anger.card.dart';
import 'package:spire_mvp_flutter/classes/card/bash.card.dart';
import 'package:spire_mvp_flutter/classes/card/body_slam.card.dart';
import 'package:spire_mvp_flutter/classes/card/clash.card.dart';
import 'package:spire_mvp_flutter/classes/card/cleave.card.dart';
import 'package:spire_mvp_flutter/classes/card/clothes_line.card.dart';
import 'package:spire_mvp_flutter/classes/card/defend.card.dart';
import 'package:spire_mvp_flutter/classes/card/flex.card.dart';
import 'package:spire_mvp_flutter/classes/card/headbutt.card.dart';
import 'package:spire_mvp_flutter/classes/card/heavy_blade.card.dart';
import 'package:spire_mvp_flutter/classes/card/iron_wave.card.dart';
import 'package:spire_mvp_flutter/classes/card/perfect_strike.card.dart';
import 'package:spire_mvp_flutter/classes/card/strike.card.dart';

final strikeCard = StrikeCard();
final bashCard = BashCard();
final defendCard = DefendCard();
final angerCard = AngerCard();
final bodySlamCard = BodySlamCard();
final clashCard = ClashCard();
final cleaveCard = CleaveCard();
final clothesLineCard = ClothesLineCard();
final flexCard = FlexCard();
final headbuttCard = HeadbuttCard();
final heavyBladeCard = HeavyBladeCard();
final ironWaveCard = IronWaveCard();
final perfectStrikeCard = PerfectStrikeCard();
